config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  
  root 'pages#index'
  get 'index', to: 'pages#index'
  get 'info', to: 'pages#info'
  get 'media', to: 'pages#media'
  get 'admin', to: 'admin#new'
  get 'admin_dashboard', to: 'admin#admin_dashboard'
  get 'logout', to: 'admin#logout'
  
  resources :pages
  resources :admin
  resource :pages, only: [:admin] do
    collection do
      patch 'check'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
    
    
    def new
    end

  def create
    user = Admin.first
    if user.password == session[:password]
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      render 'new'
    end
  end

  def destroy
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
mount_uploader :video, VideoUploader  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def new
    end

  def create
    user = Admin.first
    if user.password == params[:session][:password]
        session[:current_user] = "admin"     
        redirect_to admin_dashboard_path
    else
    redirect_to admin_path
    end
  end

  def destroy
  end
  
    def admin_dashboard
        @videos = Page.all  
    end
    
    def logout
        if session[:current_user] != "admin"
           redirect_to index_path 
        
        else
            session[:current_user] = nil
            redirect_to index_path
        end
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def index
       
        @videos = Page.all
    end
    
    def new
        if session[:current_user] != "admin"
           redirect_to index_path 
        else
            
            @page = Page.new
        end
    end

    def create
        if session[:current_user] != "admin"
           redirect_to index_path 
        else
            @page = Page.create!(page_params)
        
            redirect_to admin_dashboard_path
        end
    end
    
    def page_params
        params.require(:page).permit(:post, :title, :body, :video)
    end
    
    def info
       
    end
    
    def show
        if session[:current_user] != "admin"
           redirect_to index_path 
        else
            id = params[:id]
            @video = Page.find(id)
        end
    end
    
    def edit
        if session[:current_user] != "admin"
           redirect_to index_path 
        else
            id = params[:id]
            @page = Page.find(id)
        end
    end
    
    def update
        if session[:current_user] != "admin"
           redirect_to index_path 
        else
            @page = Page.find params[:id]
            @page.update_attributes!(page_params)
            flash[:notice] = "#{@page.title} was successfully updated."
            redirect_to page_path(@page)
        end
    end
    
    def destroy
        if session[:current_user] != "admin"
           redirect_to index_path 
        else
            @page = Page.find(params[:id])
            @page.destroy
        
            redirect_to admin_dashboard_path
        end
    end
    
   
    
    
    
    
    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/admin_dashboard.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
     <%= stylesheet_link_tag "carousel", media: 'all'%>
  </head>
  <body>

    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <%= link_to "Roach" , index_path, class: "navbar-brand" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Home" , index_path, class: "nav-link" %><span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <%= link_to "Info" , info_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Media" , media_path, class: "nav-link" %>
            </li>
             <li class="nav-item">
              <%= link_to "Create new post" , new_page_path, class: "nav-link" %>
            </li>
             <li class="nav-item">
              <%= link_to "Log out" , logout_path, class: "nav-link" %>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
          </form>
        </div>
      </nav>
    </header>

    <main role="main">

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>One more for good measure.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>


      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

     

        <!-- Three columns of text below the carousel -->
        


        <!-- START THE FEATURETTES -->

        

        <% @videos.each do |x| %>
        <center>
         
        <h1><%= x.title %></h1>
        <br>
        <h4><%= x.body %></h4></center>
        <br>
         <%= video_tag x.video_url.to_s, :controls =>true %>
        <br>
        <%= link_to "edit this post" , page_path(x) %>
        <hr class="featurette-divider">
        <% end %>

        

        <!-- /END THE FEATURETTES -->

    <!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
       <%= link_to "Back to top" , index_path, class: "float-right" %>
        <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../../../assets/js/vendor/holder.min.js"></script>
  </body>
</html>

app/views/admin/new.html.erb
<html>
  

<center><div style=" width:25%">
  
<h2>Please fill out the information below</h2>
<br>


     <%= form_for(:session) do |f| %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    

<% end %>
</div></center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<html>
  

<center><div style=" width:25%">
  
<h2>Please fill out the information below</h2>
<br>
<%= form_for @page do |f| %>

    <%= f.label "Post Title" %> <br>
    <%= f.text_field :title, class: "form-control" %> <br>
    <br>
    <%= f.label "Post Body" %> <br>
    <%= f.text_area :body, class: "form-control" %> <br>
    <br>
    <%= f.label "Video" %> <br>
    <%= f.file_field :video, class: "form-control" %> <br>
    <br>
    <%= f.submit class: "btn btn-default" %>

<% end %>
</div></center>

app/views/pages/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
     <%= stylesheet_link_tag "carousel", media: 'all'%>
  </head>
  <body>

    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <%= link_to "Roach" , index_path, class: "navbar-brand" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Home" , index_path, class: "nav-link" %><span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <%= link_to "Info" , info_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Media" , media_path, class: "nav-link" %>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
          </form>
        </div>
      </nav>
    </header>

    <main role="main">

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>One more for good measure.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>


      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

     

        <!-- Three columns of text below the carousel -->
        


        <!-- START THE FEATURETTES -->

        

        <% @videos.each do |x| %>
        <center>
         
        <h1><%= x.title %></h1>
        <br>
        <h4><%= x.body %></h4></center>
        <br>
         <%= video_tag x.video_url.to_s, :controls =>true %>
        <br>

        <hr class="featurette-divider">
        <% end %>

        

        <!-- /END THE FEATURETTES -->

    <!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
       <%= link_to "Back to top" , index_path, class: "float-right" %>
        <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../../../assets/js/vendor/holder.min.js"></script>
  </body>
</html>

app/views/pages/new.html.erb
<html>
  

<center><div style=" width:25%">
  
<h2>Please fill out the information below</h2>
<br>
<%= form_for @page do |f| %>

    <%= f.label "Post Title" %> <br>
    <%= f.text_field :title, class: "form-control" %> <br>
    <br>
    <%= f.label "Post Body" %> <br>
    <%= f.text_area :body, class: "form-control" %> <br>
    <br>
    <%= f.label "Video" %> <br>
    <%= f.file_field :video, class: "form-control" %> <br>
    <br>
    <%= f.submit class: "btn btn-default" %>

<% end %>
</div></center>

app/views/pages/show.html.erb
<%= link_to "edit this post", edit_page_path(@video) %>
<br>


<%= link_to "back to dashboard", admin_dashboard_path %>
<br>

<%= @video.title %>
<br>
<%= @video.body %>

<%= video_tag @video.video_url.to_s, :controls =>true %>

<%= button_to "delete this post", @video, :method => :delete %>